void printWifiStatus();
void telnetReadline();
void serialReadline();
void cmdSaveConfig();
void cmdClearConfig();
void cmdGetConfig();
void cmdSsid();
void cmdDisplay();
void cmdPassword();
void cmdNtpServer();
void cmdShowState();
void cmdInitUpdate();
void cmdSyncUpdate();
void cmdSyncValid();
void cmdShowVersion();
void cmdShowTime();
#ifdef __MK1_HW
void cmdWiFiVersion();
#else
void cmdCopy();
void cmdDelete();
void cmdDirectory();
void cmdDump();
void cmdFormat();
void cmdRename();
void cmdHostname();
void cmdTypeFile();
void cmdFtpUsername();
void cmdFtpPassword();
void cmdReboot();
#endif
void cmdWebConfig();
void cmdListCommands();
void commandInterpretter();
